### ISSUE TITLE
Typelib file for namespace 'Gdk' (any version) not found

### ISSUE THREAD

**Issue by Pablo1107** [mut-ex/awesome-wm-nice#1]
I got this error when nice is import `lgi.Gdk`. I'm running NixOS and it's probably because of some weird wrapping missing the dependency needed here.

```
error ...9jf60-lua5.2-lgi-0.9.2-1/share/lua/5.2/lgi/namespace.lua:158: Typelib file for namespace 'Gdk' (any version) not found
```

**Comment by Pablo1107** [comment]
Related issue in NixOS/nixpkgs#60538

**Comment by Pablo1107** [comment]
Fixed by adding `gtk3Support` to awesome through an overlay like this:
```
  nixpkgs.overlays = [
    (self: super:
    {
      awesome = super.awesome.override {
        gtk3Support = true;
      };
    })
  ];
```

**Comment by anirrudh** [comment]
@Pablo1107 you the best, thanks!

**Comment by mut-ex** [comment]
@Pablo1107 Thank you for finding the solution to this. I have updated the README.
