### ISSUE TITLE
Feature request: have titlebar only when window is floating

### ISSUE THREAD

**Issue by Pablo1107** [mut-ex/awesome-wm-nice#12]
Adding to the features you're adding maybe another thing may be a setting that allows the titlebar only to show if the window is on floating mode.

**Comment by maaaaf** [comment]
> Additionally, nice only adds window decorations to clients that have the titlebars_enabled property set to true. So configure your client rules accordingly.

maybe you can use [rules](https://awesomewm.org/doc/api/libraries/awful.rules.html) to enable the title bar for the floating window.

**Comment by Pablo1107** [comment]
> > Additionally, nice only adds window decorations to clients that have the titlebars_enabled property set to true. So configure your client rules accordingly.
> 
> maybe you can use [rules](https://awesomewm.org/doc/api/libraries/awful.rules.html) to enable the title bar for the floating window.

Those rules don't affect the titlebar when switching tiling/floating, and other things.

**Comment by maaaaf** [comment]
> > > Additionally, nice only adds window decorations to clients that have the titlebars_enabled property set to true. So configure your client rules accordingly.
> > 
> > 
> > maybe you can use [rules](https://awesomewm.org/doc/api/libraries/awful.rules.html) to enable the title bar for the floating window.
> 
> Those rules don't affect the titlebar when switching tiling/floating, and other things.

what about signal?

I found some discussions about this.

[https://www.reddit.com/r/awesomewm/comments/box4jk/my_functional_dynamic_border_gap_and_titlebar/](https://www.reddit.com/r/awesomewm/comments/box4jk/my_functional_dynamic_border_gap_and_titlebar/)

**Comment by Pablo1107** [comment]
@maaaaf yes, I have some signals to workaround this. But I'm also using a feature branch of awesome which corrects some issues when removing/adding titlebars to clients. I'm actually waiting for that to be merge and will make a PR with this feature here.

**Comment by mut-ex** [comment]
The problem is nice adds "titlebars" on all four sides of the window to create the border plus the anti-aliased corners. So what would be the desired behavior:

a) Remove all the window decorations from tiled windows. You can maximize screen real-estate that way.
or
b) Keep the window decorations but create a very small titlebar at the top so that tiled and floating windows follow a consistent style.

Neither of those options are a hassle to implement but I am curious about what would people prefer.

**Comment by Pablo1107** [comment]
> The problem is nice adds "titlebars" on all four sides of the window to create the border plus the anti-aliased corners. So what would be the desired behavior:
> 
> a) Remove all the window decorations from tiled windows. You can maximize screen real-estate that way.
> or
> b) Keep the window decorations but create a very small titlebar at the top so that tiled and floating windows follow a consistent style.
> 
> Neither of those options are a hassle to implement but I am curious about what would people prefer.

I imagine **b** is the correct option here, but currently I'm doing **a** because lazyness.
