### ISSUE TITLE
Scroll-up/down the window shade feature doesn't work anymore in master branch

### ISSUE THREAD

**Issue by raven2cz** [mut-ex/awesome-wm-nice#13]
Feature Window Shade:
Scroll-up with your mouse over the titlebar to "roll-up" the window shade. Scroll-down over the titlebar, or left-click to "roll-down" the window shade

It doesn't work anymore in my last tests. I tried to activate feature too with parameter win_shade_enabled = true, but without success.

In addition, is it possible to change behaviour, to MOVE roll-up window WITHOUT roll-down. It means to keep window still roll-up when you are moving the window. Not to roll-down it when I try to move it....just idea.

**Comment by mut-ex** [comment]
Sorry about that. Fixed the problem and window shade works again.

Also, I changed the behavior, so now you can move a "rolled-up" window without triggering a roll-down. It's a good suggestion and I had the same idea initially but was too lazy to implement it before lol
