### ISSUE TITLE
key bindings not working

### ISSUE THREAD

**Issue by frodo4fingers** [mut-ex/awesome-wm-nice#16]
having nice loaded/initialized appears to completely disable nearly all key bindings i have

**Comment by mut-ex** [comment]
Nice doesn't add/touch any key bindings. Only mouse button bindings for the window decorations. Can you provide more detail about the kinds of key bindings you have?

**Comment by frodo4fingers** [comment]
can't. other that i didn't use awesome's git branch... clearly i didn't read. everysthing got solved by using awesome-git :-)
sry for bothering!
