### ISSUE TITLE
custom titlebar text color

### ISSUE THREAD

**Issue by branwright1** [mut-ex/awesome-wm-nice#19]
How can I change titlebar text color? I don't see any property for it :(

**Comment by mut-ex** [comment]
Currently nice calculates the luminescence of the client color relative to `title_color_dark` and `title_color_light` in the `init.lua`. And then selects the either the dark or light color based on the contrast ratio. You can change those in the `init.lua` file if you'd like. Other than that, there isn't a way to specify titlebar text color on a per client basis.

**Comment by branwright1** [comment]
Thanks for reply and good explaination.
