### ISSUE TITLE
attemp to index a nil value (field 'names')

### ISSUE THREAD

**Issue by aspieln3r** [mut-ex/awesome-wm-nice#2]
adding nice to my awesomewm configuration gives me this error
```
2020-09-01 14:50:26 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/home/fsinft/.config/awesome/nice/init.lua:313: in upvalue 'create_titlebar_button'
	/home/fsinft/.config/awesome/nice/init.lua:485: in upvalue 'create_titlebar_items'
	/home/fsinft/.config/awesome/nice/init.lua:660: in field 'add_window_decorations'
	/home/fsinft/.config/awesome/nice/init.lua:837: in function </home/fsinft/.config/awesome/nice/init.lua:813>
	[C]: in method 'emit_signal'
	/usr/share/awesome/lib/awful/rules.lua:697: in function 'awful.rules.execute'
	/usr/share/awesome/lib/awful/rules.lua:494: in function 'awful.rules.apply'
error: /home/fsinft/.config/awesome/nice/init.lua:313: attempt to index a nil value (field 'names')
```
I tried commenting out the default `client.connect_signal("request::titlebars"...` entirely and only `awful.titlebar(c) : setup` but no change.

**Comment by aspieln3r** [comment]
I replaced the names table references with the original key id. Now the errors are gone but I dont have a working titlebar. An empty title bar is drawn with rounded borders but there are no buttons and its not functional

**Comment by aspieln3r** [comment]
```
awesome -v
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by raven2cz** [comment]
I had same problems with release version v4.3. I tried with git master version v4.4+ and it works with it.

**Comment by mut-ex** [comment]
I am going to give it a try on the non-git version but the error you are getting is basically because I am using named constants instead of button numbers. If you want a quick fix for that change the lines where you see   `awful.button.names... `
with 1 for left button and 2 for right button. And 4 for scroll up and 5 for scroll down. I am not yet sure if you will run into any other problems with that fixed.

**Comment by aspieln3r** [comment]
@mut-ex 
I tried it. errors are no longer there but the title bar is not functional and doesnt show any buttons and colors are glitchy. Might be that you are not developing this for stable version. Can we expect support for stable version?

**Comment by anirrudh** [comment]
@mut-ex getting the same issue on nixOS :( any ideas on what this could be?

**Comment by raven2cz** [comment]
The main reason is that the API between 4.3 and 4.4+ (git-master version, which is not still released) is very different. There are a lot of not backward incompatibilities. AwesomeWM makes changes like between major versions, not minor versions. If you check for example rc.lua default file between release version 3.4 and git-master branch, there are large structural changes, mainly listener approach and events notification framework. Previous version has many structural mistakes, it was a one circle in awful object. New git-master version tries to solve correct encapsulation to concrete modules and instances + enhanced listener support. 
In my opnion, it cannot be easly modify some library like this one for both "worlds". Technically it means to write whole project again for older "release" version.
But it has to define by owner / developer of this project...

**Comment by mut-ex** [comment]
Good news! :) I was able to make changes to nice to make it compatible with Awesome v4.3 stable. However the version for Awesome stable isn't compatible with Awesome git and vice-versa. [**Therefore I created a new branch**](https://github.com/mut-ex/awesome-wm-nice/tree/awesome-4v3-stable). Unfortunately the window shade feature isn't fully functional yet so it is disabled by default.  But everything else works! If you find any bugs please do share.
