### ISSUE TITLE
Missing titlebars

### ISSUE THREAD

**Issue by JeremyStarTM** [mut-ex/awesome-wm-nice#28]
I just installed the nice version for Awesome 4.3 (which I am using). I am on Manjaro Linux, and my titlebars are gone. I followed the README exactly. I don't know what went wrong here. I didn't change any files of awesome, except the init.lua because of issue #24.

**Comment by fIzzieBots** [comment]
Do you have titlebars_enabled set to true? I thought I had to remove those lines but they are necessary, not sure but  that might fix your problem.

**Comment by JeremyStarTM** [comment]
I have them disabled already and it doesn't fix it.

**Comment by fIzzieBots** [comment]
Sorry if I wasn't clear, they need to be enabled and set to true. I did this, and it technically solved this issue, but it breaks in a different way this time.
