### ISSUE TITLE
Shadows not painted.

### ISSUE THREAD

**Issue by raven2cz** [mut-ex/awesome-wm-nice#3]
I tried my previous settings of shadows, and your described shadow configuration in picom, but the shadows are not painted anymore if the nice() is initialized. If the feature is not activated, the shadows are painted.

**Comment by raven2cz** [comment]
I solved the problem now! I had activated this feature for rounded corners:
shadow-ignore-shaped = true;
In your case, the feature has to be set to:
shadow-ignore-shaped = false;
The shadows are painted successfully now!

**Comment by Pablo1107** [comment]
I had the same thing on my system, turning that setting of solves it. Please close this issue @raven2cz .
