### ISSUE TITLE
Transparent, nonfunctional titlebars.

### ISSUE THREAD

**Issue by fIzzieBots** [mut-ex/awesome-wm-nice#30]
I installed nice on my awesomeWM configuration recently, but the titlebars aren't working correctly. I have titlebars_enabled set to true in my rules, other titlebar-related pieces of code in my rc.lua commented out. My issue is that the titlebars are appearing, with slight shadows behind them, but they are completely transparent and do not function. I'm using awesomeWM 4.3, lua 5.3, and ibhagwan's picom fork.
![niceerr](https://user-images.githubusercontent.com/86626165/153525274-b77d9c24-34d4-40ba-a90a-03d1614c0646.png)

**Comment by Nineswiss** [comment]
I also have this issue :/

**Comment by MTHLily** [comment]
I had the same problem. I switched over to the git version of awesomewm and it fixed this.
