### ISSUE TITLE
GTK4 supported?

### ISSUE THREAD

**Issue by zhisme** [mut-ex/awesome-wm-nice#38]
Recently installed GTK4 due to some app needed it as dependency, and now I'm getting when trying to require nice in my `rc.lua` 
![image](https://user-images.githubusercontent.com/13069050/210744491-3e4f1ea2-990d-4459-abeb-7b0644c86065.png)
`awesome/nice/init.lua:79: attempt to call a nil value (field 'init')`
I'm sure that it is somehow related to GTK4, and when I deleting GTK4 nice is working nice :smile: 

However when GTK4 installed, I just commenting `require nice` in `rc.lua` and all working as expected. I tried to understand whether GTK4 supported or not, but can't find any sign. Maybe there's some option to force use GTK3 (which was working totally fine with awesome and nice)
my `~/.config/gtk-3.0/settings.ini` `~/.config/gtk-4.0/settings.ini` contains information from readme. Tried to remove last one 4.0 but didn't make anything, still can't load with nice enabled in `rc.lua`

```
awesome v4.3-1360-gc539e0e43 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version:  0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

And I'm using latest  git master `nice` with commit `810aa72`

Does anyone successfully use nice with GTK4? Is there any recipe? Either tell me what I'm missing or it is not supported, thanks

**Comment by Aire-One** [comment]
Fixed by https://github.com/mut-ex/awesome-wm-nice/pull/25, but no news from the author.

I suggest you to apply the fix manually on your local copy of the module.

**Comment by zhisme** [comment]
@Aire-One great thanks, applied the changes and that had fixed my issue. Works fine with GTK4
