### ISSUE TITLE
Gdk.lua bug - Nice not working

### ISSUE THREAD

**Issue by MightyPancake** [mut-ex/awesome-wm-nice#39]
Hello, I'm running the awesome-git version with nice (or at least, trying to), but unfortunately the following error occurs:
```
/usr/share/lua/5.4/override/Gdk.lua: 23 bad argument #1 to 'registerlock' (userdata expected, got nil)
```

Any ideas on how to fix it?
Running lastest Manjaro
Awesome Version:
```
awesome v4.3
Compiled against Lua 5.5.5 (running with 0.9.2)
LGI version: 0.9.2
```

**Comment by Aire-One** [comment]
Hello, with Awesome stable 4.3, you have to use the `awesome-4v3-stable` branch of this repository https://github.com/mut-ex/awesome-wm-nice/tree/awesome-4v3-stable.

**Comment by MightyPancake** [comment]
```
[filip@Juliette awesome]$ git clone https://github.com/mut-ex/awesome-wm-nice.git --single-branch --branch awesome-4v3-stable nice
Cloning into 'nice'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 46 (delta 16), reused 14 (delta 14), pack-reused 24
Receiving objects: 100% (46/46), 4.12 MiB | 8.01 MiB/s, done.
Resolving deltas: 100% (22/22), done.
[filip@Juliette awesome]$ awesome -v
awesome v4.3-1588-gb54e50ad6 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
 ```
 
 Tried it with both, both return the same error(?)

**Comment by MightyPancake** [comment]
@Aire-One

**Comment by MightyPancake** [comment]
Ok, got it running. Turns out I had ```GTK 4``` installed and it took over, **BUT** it's LGI is not compatible with it. For future people with this issue the solution is just uninstalling ```sudo pacman -S gtk4```.
Works like a charm!

**Comment by Aire-One** [comment]
If the issue was indeed GTK, https://github.com/mut-ex/awesome-wm-nice/pull/33 should resolve it without you uninstalling GTK4. (maybe the correct fix is `local gdk = lgi.require('Gdk', '3.0')`)
