### ISSUE TITLE
Titlebars default modification destroys your settings.

### ISSUE THREAD

**Issue by raven2cz** [mut-ex/awesome-wm-nice#4]
I found the problem after first usage that your titlebars are not used.
Because in standard configuration rc.lua is modification of titlebars which delete your titlebars and settings:
For example:
**client.connect_signal("request::titlebars", function(c)**
this configuration change your modification.
Please add to your installation notes, that the changes of titlebars in lua code has to be commented/not used. Because your settings replace these modifications.
In any cases, nice works for NICE! Thanks!

**Comment by mut-ex** [comment]
Thank you! I updated the README instructions to reflect that. :)
