### ISSUE TITLE
Too long titles destroy design of titlebar name

### ISSUE THREAD

**Issue by raven2cz** [mut-ex/awesome-wm-nice#5]
Too long titles has to be decreased. It kills the design of the titlebar.
See picture
![nice-long-title-bug1](https://user-images.githubusercontent.com/20504243/91849396-49f28b80-ec5c-11ea-97d1-8acfb5217f9d.png)

**Comment by mut-ex** [comment]
Thanks for bringing this up. I am working on it.

**Comment by Pablo1107** [comment]
In case you didn't worked on it yet (hope you didn't lol), I came forward and fixed it.

**Comment by mut-ex** [comment]
Latest commit fixes this issue.
