### ISSUE TITLE
Nice to have according to standard titlebar behaviours

### ISSUE THREAD

**Issue by raven2cz** [mut-ex/awesome-wm-nice#6]
There is just two nice to have features which can improve your NICE titlebar ;-)
I'm using in standard title bar this configuration:
-- buttons for the titlebar
    local buttons = {
        awful.button({ }, 1, function()
            c:activate { context = "titlebar", action = "mouse_move"  }
        end),
        awful.button({ }, 2, function()
            c:activate { context = "titlebar", action = "mouse_resize"}
        end),
    }

The mouse_move feature is supported by your solution, but mouse_resizing doesn't work because you are using popup menu for coloring feature. Can you add posibility to configure mouse buttons? For example:
left mouse button (1) - for window movement
middle mouse button (2) - for popup coloring feature
right mouse button (3) - resizing window

**Comment by mut-ex** [comment]
Good suggestion! I'll add the button as a configurable option.

**Comment by mut-ex** [comment]
Added the option to configure mouse button bindings for titlebar actions in the latest commit.
