### ISSUE TITLE
Small, minor, unimportant "optimisation"

### ISSUE THREAD

**Issue by psychon** [mut-ex/awesome-wm-nice#8]
Hi,

I just randomly looked through this and found this code:
https://github.com/mut-ex/awesome-wm-nice/blob/04bab00b464039702756d5dd812aea754a907a95/colors.lua#L15-L30
I think this can be replaced with `gears.color.parse_color()`. Feel free to decide if you like that or not and just close this issue. I just wanted to let you know about it.

Also: Nice work. Looks really good.

**Comment by mut-ex** [comment]
Thank you for pointing that out. That's a good suggestion and I think I will use ` gears.color.parse_color()` instead. Also if there are any other improvements/optimizations you can suggest I'd really appreciate it. And thank you for the compliment!
